{% set name = "numina" %}
{% set version = "0.21" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8c13a3a9f3a48cdf675b1671607157d5df7979d994c0eba521296edd0a88a9a3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  entry_points:
    - numina = numina.user.cli:main
    - numina-apply_integer_offsets = numina.array.wavecalib.apply_integer_offsets:main
    - numina-bpm = numina.array.bpm:main
    - numina-check_wlcalib = numina.array.wavecalib.check_wlcalib:main
    - numina-imath = numina.tools.imath:main
    - numina-r6-addnf = numina.tools.r6_addnf:main
    - numina-r6-imcombine = numina.tools.r6_imcombine:main
    - numina-r6-insert_keyword = numina.tools.r6_insert_keyword:main
    - numina-r6-replace_image = numina.tools.r6_replace_image:main
    - numina-wavecalib = numina.array.wavecalib.__main__:main
    - numina-ximshow = numina.array.display.ximshow:main
    - numina-ximplotxy = numina.array.display.ximplotxy:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - numpy
    - python
    - setuptools
  run:
    - python
    - setuptools
    - six >=1.7
    - {{ pin_compatible('numpy') }}
    - astropy >=2
    - scipy
    - scikit-image
    - pyyaml
    - matplotlib
    - enum34  # [py27]
    - contextlib2  # [py27]
    - python-dateutil
    - lmfit

test:
  imports:
    - numina
    - numina.array
    - numina.array.display
    - numina.array.peaks
    - numina.array.peaks.tests
    - numina.array.tests
    - numina.array.trace
    - numina.array.trace.tests
    - numina.array.wavecalib
    - numina.array.wavecalib.tests
    - numina.core
    - numina.core.tests
    - numina.dal
    - numina.dal.tests
    - numina.drps
    - numina.drps.tests
    - numina.drps.tests.configs
    - numina.ext
    - numina.ext.gtc
    - numina.frame
    - numina.frame.tests
    - numina.instrument
    - numina.instrument.components
    - numina.instrument.components.tests
    - numina.instrument.simulation
    - numina.instrument.tests
    - numina.modeling
    - numina.modeling.tests
    - numina.processing
    - numina.store
    - numina.store.gtc
    - numina.store.tests
    - numina.tests
    - numina.tools
    - numina.tools.tests
    - numina.types
    - numina.types.tests
    - numina.user
    - numina.user.tests
    - numina.util
    - numina.util.tests
  commands:
    - numina --help
#    - py.test --pyargs numina
  requires:
    - pytest

about:
  home: http://guaix.fis.ucm.es/projects/numina
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Astronomy data reduction library
  description: |
    Numina is a data reduction library for astronomy
    used by the following Gran Telescopio Canarias
    instruments: EMIR, FRIDA, MEGARA and MIRADAS.
  doc_url: http://numina.readthedocs.io/
  dev_url: https://github.com/guaix-ucm/numina

extra:
  recipe-maintainers:
    - sergiopasra
