appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OKMGakMOccx8yroMThBJahNX8XjMHbuJt7QkvY0UChtCgR+9DG9+W3txOMDUrf+LSbE+IG4j/fWo6tl5lhkqoBDT1fekV0uP6Q6YekUm75aSPwlHrM0srxEAG9VeBRSdUyWIDukIa5aYq9VPNJivQgs8pQmaHfFK2pRSKcVZFVUsmKrmG60NnAUKILWlgpc8y15Uo/CIar6xtaYTWsMmA+pvpkoXPji0ROLsekB7LdIpj/RzBtYjc1Hl7mArk9FivC5P4db6VeUJc93mL1d4tJGOJphfUX3aYLHFymKN1+PtQrK4Wbj+gCsYfYbrFbd5cOQcMhCTYwpOp9936zjof9djT0E17K3EDuWMeRa8+6shRr29DFPkcw1EaPpDqv5mstpTTHJ7iemwxwGlQ66Ptup/whDTVfmuIDZiOiAvCKoISxvCAKV/JF6jwvoVrPsHRSaAxW8ZgkiMCvPfLUgZlKVj5vjciqv7+QfJIw3ilEgShyKpflletI7ZbBgpinWPkUZ6JMiwhF6JfdsvvgBaXKRXJftV/9oBI7krdxMr2UG6925JFi91fV80iFv84YcQ8R29fRGxZ+uMvWPvPB61tDduCkTOrBpEQ+9prSyMYJY7jcMwsUKnnfIpjfNYlCMIbjSTZ2VIQdoe0jiQQnbmjwlctkfVgyb3Xo9Xu8x8Ges=}
provider:
  win: azure
