travis:
  secure:
    BINSTAR_TOKEN: xPzlkvmMuZrvqQ/RGHGDJsqhLEBAn5DYAlXD1+oQJdDFMzVCIbNO65Xynyy2AU0Nq8pMoOQTKY3WAgWH33KQW9R3MNrRx8WgweTz1OX82XSLe99v5uCGJ4gw7meP+nXKAT2XO6D0LeuXaLKAlK50PHpV0aQn+WdUCpuiFJay1hRy/MuqHDDjSk8lBB/Fsn0nyaCEqaFkr3gHvx2Uob8//nVuNBbp0r09+5PiRW3ysy0BRKOMka536CuBK7DSZm0aVOWWZSWfzdOjeMddGnuijavM9IzGx8Z0FMpAo31fFHvfYNDjsuuhSnIEODD3m3RUzDw41kAjSyNOJqWpxv8azSHsaM+c2AfmhrUXE33fE1avIdMSLPp5glHaQKTZLi6rnU+i9zBBlJU5lukWNar06ocPZ+2I3xbWwfJzUoNhOd9aKaHW7LO1NaqYMFiYBRXrg/TH7vRsxCmH9K7mZLmvCf4VNusEFTO9TOw3uUKwuvsfJBFrvvic9wqntNqUk6osiab5rqwmHMyohyok8gmrnG+jlSTEtFit19WCN2t9HZ/G/vBUylWnvpEeLAgXIJU3IX/MFj/kkY5FEi76JMfzYf+mx/rVWvE2UO9mu/mPuR5kv3Nzzp3/jy078HMNJX6z6dDti+LFz62OnBt+yOHrVNnEcWyKJXZe2aPp40tyD8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
