travis:
  secure:
    BINSTAR_TOKEN: gHtC+hgrbFzRsEBfwXHUtXMq5sjc+pIvSSu49TDIv5m03eNC/ahhriJQRqb3qmtZaVo+8pEdO8XP85botZBf+URQPQbgkxZJ3msK2kbATX1bqN3H1/OltKcbKG8D1WDNhDgnLIGfqXOJMoQrP6P9k2Kx5SXbc1eBnnG7YnYomV8dyV7ze25FQnEU5S/s88/lqDHh7CYUCJcJBe2vzpZFgKcxl2TI40BlZ1SKpktGsvBk/EyWszc+gnYhdCpDEkjw2sugtpReOjILeel0wjIVFSwF7C/uybl1QpDdd3MCwmZOV+Pm1W2QtfSUckgqsLP3v90Vy0sv8lrtsSdpScx1plE7ad5lb+9TY+znJa4agtBXyscqahIOjJRXRkX5Kviik20lGjmZ2mLSVryzZzcebVmqXAuvjtPGaLcJyVZxY8bL1eGY0jd8q65JIZpnZL+Aru144xzLhXD3c+AZ4bLztUCkmJr3n1QMKanc+EG1+UNrc0scIafGwz4Fx3gmy63vPOedyRQWZ2nHg+qIuKUuNdyFdFR7Fw0dPJHhtpn2UV+gAZdhXryqzaXZwUH2AeEnZ6ruvICGWWrNK/9i/Z4fUtSRfYFgHBCF7pNc/87uMMvSTXkBBug5Zi9DsC73D/4gObNdSSPhnDBnERNkwWJk2+NTVOhTjqjZb1CY0FxCozA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
